import {boxShadowLight, borderLight} from "../../../../../core/style/constant";

const style = (theme) => ({
    root: {
        paddingBottom: 30,
        position: "relative",
    },
    circle: {
        display: "flex",
        position: "relative",
        margin: "0px 25px",
    },
    thermostat: {
        top: 50,
        left: 50,
        width: 230,
        height: 230,
        background: theme.palette.background.light,
        boxShadow: boxShadowLight,
        position: "absolute",
        borderRadius: "100%",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "column",
    },
    thermostatInner: {
        top: 30,
        left: 30,
        width: 170,
        height: 170,
        display: "flex",
        zIndex: 5,
        position: "absolute",
        background: "#3d4058",
        boxShadow: "0px 0px 20px rgb(13 14 14 / 53%)",
        alignItems: "center",
        borderRadius: "100%",
        flexDirection: "column",
        justifyContent: "center",
        transition: "0.2s",
    },
    currentTemperature: {
        display: "flex",
    },
    currentTemperatureText: {
        fontSize: "2.5rem",
        fontWeight: 400,
    },
    currentRoomText: {
        fontSize: "1.2rem",
        fontWeight: 300,
    },
    currentTemperatureLabel: {
        fontSize: "1.5rem",
        fontWeight: 300,
        lineHeight: "65px",
        marginLeft: 5,
    },
    askTemperature: {
        display: "flex",
    },
    askTemperatureText: {
        fontSize: "1.5rem",
        fontWeight: 300,
    },
    askTemperatureLabel: {
        fontSize: "1.2rem",
        fontWeight: 300,
        lineHeight: "38px",
        marginLeft: 5,
    },
    wheather: {
        display: "flex",
        alignItems: "center",
    },
    outDoor: {},
    outDourTemperature: {
        fontSize: "1.6rem",
        fontWeight: 300,
        lineHeight: "38px",
        marginLeft: 5,
    },
    outDourTemperatureMin: {
        fontSize: "0.8rem",
        fontWeight: 300,
        marginRight: 2,
        textAlign: "right",
    },
    divider: {
        borderLeft: borderLight,
        height: 66,
        margin: "0 10px",
    },
    weatherInfo: {
        display: "flex",
        alignItems: "center",
        margin: "4px 0",
    },
    weatherInfoIcon: {
        marginRight: 7,
    },
    weatherCloudIcon: {
        width: 60,
        height: 60,
        margin: "auto",
        display: "block",
        marginBottom: "-10px",
        marginTop: "-10px",
    },
    controlPanel: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        marginTop: "-30px",
    },
    controlButton: {
        padding: "10px 25px",
        textAlign: "center",
        margin: "0 !important",
        border: "none",
        backgroundColor: "inherit",
        borderRadius: 0,
        minWidth: 0,
        width: "-webkit-fill-available",
        "&:hover": {
            backgroundColor: "transparent",
        },
    },
    controlButtonTop: {
        padding: "10px 25px",
        borderBottom: theme.palette.border.dark,
        textAlign: "center",
        margin: "0 !important",
        border: "none",
        backgroundColor: "inherit",
        borderRadius: 0,
        minWidth: 0,
        width: "-webkit-fill-available",
        "&:hover": {
            backgroundColor: "transparent",
        },
    },
    controlButtonBottom: {
        padding: "10px 25px",
        borderTop: theme.palette.border.dark,
        textAlign: "center",
        margin: "0 !important",
        border: "none",
        backgroundColor: "inherit",
        borderRadius: 0,
        minWidth: 0,
        width: "-webkit-fill-available",
        "&:hover": {
            backgroundColor: "transparent",
        },
    },
    controlButtonTarget: {
        color: theme.palette.primary.main,
    },
    gauge: {
        position: "absolute",
        top: "-56px",
        left: "-31px",
        width: 446,
    },
    cursor: {
        position: "absolute",
        top: 31,
        left: 71,
        width: 300,
        transformOrigin: "39.7% 44.2%",
        transition: "0.5s",
    },
    temperatureText: {
        display: "flex",
        justifyContent: "space-between",
        width: 250,
        position: "absolute",
        top: 298,
        left: 69,
    },
});

export default style;
